version: '3.3'

services:
   mysql:
    image: 'mysql:5.7.22'
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: urlsho_user
      MYSQL_PASSWORD: urlsho_pass
      MYSQL_DATABASE: urlsho_db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - database
    volumes:
      - "./conf/mysql:/docker-entrypoint-initdb.d"
      - db-data:/var/lib/mysql

   api:
     build:
       context: .
       dockerfile: Dockerfile
     networks:
       - database
     ports:
       - "8080:8080"

volumes:
  db-data:

networks:
  database:
