version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/soeyusuke/url_shorter
    steps:
      - checkout

      - run: go get -v ./base62
#      - run: go test -v ./...
